/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef V1_COMMONAPI_FCS__SLIF__IHBC__Status__Service_SOMEIP_DEPLOYMENT_HPP_
#define V1_COMMONAPI_FCS__SLIF__IHBC__Status__Service_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace FCS_SLIF_IHBC_Status_Service_ {

// Interface-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> FCS_IHBC_Status_EnumDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> FCS_IHBC_LightDistribReq_EnumDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> FCS_IHBC_Switch_EnumDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> FCS_SLIF_Switch_EnumDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> FCS_Sign_SpeedLimitCancelled_EnumDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> FCS_SLIF_Status_EnumDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> FCS_SLIF_Warning_EnumDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_IHBC_Status_EnumDeployment_t,
    ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_IHBC_LightDistribReq_EnumDeployment_t,
    ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_IHBC_Switch_EnumDeployment_t,
    ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_SLIF_Switch_EnumDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_Sign_SpeedLimitCancelled_EnumDeployment_t,
    ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_SLIF_Status_EnumDeployment_t,
    ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_SLIF_Warning_EnumDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> FCS_SLIF_IHBC_Status_StructDeployment_t;

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace FCS_SLIF_IHBC_Status_Service_
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_FCS__SLIF__IHBC__Status__Service_SOMEIP_DEPLOYMENT_HPP_
