/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_FCS__SLIF__IHBC__Status__Service_STUB_HPP_
#define V1_COMMONAPI_FCS__SLIF__IHBC__Status__Service_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/commonapi/FCS_SLIF_IHBC_Status_Service.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service FCS_SLIF_IHBC_Status_Service. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class FCS_SLIF_IHBC_Status_ServiceStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual FCS_SLIF_IHBC_Status_Service {
 public:
    ///Notifies all remote listeners about a change of value of the attribute FCS_SLIF_IHBC_Status.
    virtual void fireFCS_SLIF_IHBC_StatusAttributeChanged(const ::v1::commonapi::FCS_SLIF_IHBC_Status_Service::FCS_SLIF_IHBC_Status_Struct &FCS_SLIF_IHBC_Status) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockFCS_SLIF_IHBC_StatusAttribute(bool _lockAccess) {
        if (_lockAccess) {
            fCS_SLIF_IHBC_StatusMutex_.lock();
        } else {
            fCS_SLIF_IHBC_StatusMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex fCS_SLIF_IHBC_StatusMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for FCS_SLIF_IHBC_Status_Service.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class FCS_SLIF_IHBC_Status_ServiceStubRemoteEvent
{
public:
    virtual ~FCS_SLIF_IHBC_Status_ServiceStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service FCS_SLIF_IHBC_Status_Service to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class FCS_SLIF_IHBC_Status_ServiceStub
    : public virtual CommonAPI::Stub<FCS_SLIF_IHBC_Status_ServiceStubAdapter, FCS_SLIF_IHBC_Status_ServiceStubRemoteEvent>
{
public:

    virtual ~FCS_SLIF_IHBC_Status_ServiceStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 1);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Provides getter access to the attribute FCS_SLIF_IHBC_Status
    virtual const ::v1::commonapi::FCS_SLIF_IHBC_Status_Service::FCS_SLIF_IHBC_Status_Struct &getFCS_SLIF_IHBC_StatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireFCS_SLIF_IHBC_StatusAttributeChanged(::v1::commonapi::FCS_SLIF_IHBC_Status_Service::FCS_SLIF_IHBC_Status_Struct _value) {
    auto stubAdapter = CommonAPI::Stub<FCS_SLIF_IHBC_Status_ServiceStubAdapter, FCS_SLIF_IHBC_Status_ServiceStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireFCS_SLIF_IHBC_StatusAttributeChanged(_value);
    }
    void lockFCS_SLIF_IHBC_StatusAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<FCS_SLIF_IHBC_Status_ServiceStubAdapter, FCS_SLIF_IHBC_Status_ServiceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockFCS_SLIF_IHBC_StatusAttribute(_lockAccess);
    }


    using CommonAPI::Stub<FCS_SLIF_IHBC_Status_ServiceStubAdapter, FCS_SLIF_IHBC_Status_ServiceStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<FCS_SLIF_IHBC_Status_ServiceStubAdapter, FCS_SLIF_IHBC_Status_ServiceStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<FCS_SLIF_IHBC_Status_ServiceStubAdapter, FCS_SLIF_IHBC_Status_ServiceStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef FCS_SLIF_IHBC_Status_ServiceStubRemoteEvent RemoteEventType;
    typedef FCS_SLIF_IHBC_Status_Service StubInterface;
};

} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_FCS__SLIF__IHBC__Status__Service_STUB_HPP_
