/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/FCS_SLIF_IHBC_Status_ServiceSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createFCS_SLIF_IHBC_Status_ServiceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< FCS_SLIF_IHBC_Status_ServiceSomeIPProxy>(_address, _connection);
}

void initializeFCS_SLIF_IHBC_Status_ServiceSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.FCS_SLIF_IHBC_Status_Service:v1_0:commonapi.FCS_SLIF_IHBC_Status_Service",
        0x3335, 0x1, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "commonapi.FCS_SLIF_IHBC_Status_Service:v1_0",
        &createFCS_SLIF_IHBC_Status_ServiceSomeIPProxy);
}

INITIALIZER(registerFCS_SLIF_IHBC_Status_ServiceSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeFCS_SLIF_IHBC_Status_ServiceSomeIPProxy);
}

FCS_SLIF_IHBC_Status_ServiceSomeIPProxy::FCS_SLIF_IHBC_Status_ServiceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          fCS_SLIF_IHBC_Status_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x9950), CommonAPI::SomeIP::event_id_t(0x9950), CommonAPI::SomeIP::method_id_t(0x1950), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, static_cast< ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_SLIF_IHBC_Status_StructDeployment_t* >(nullptr))
{
}

FCS_SLIF_IHBC_Status_ServiceSomeIPProxy::~FCS_SLIF_IHBC_Status_ServiceSomeIPProxy() {
    completed_.set_value();
}

FCS_SLIF_IHBC_Status_ServiceSomeIPProxy::FCS_SLIF_IHBC_StatusAttribute& FCS_SLIF_IHBC_Status_ServiceSomeIPProxy::getFCS_SLIF_IHBC_StatusAttribute() {
    return fCS_SLIF_IHBC_Status_;
}


void FCS_SLIF_IHBC_Status_ServiceSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> FCS_SLIF_IHBC_Status_ServiceSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace commonapi
} // namespace v1
