/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COMMONAPI_FCS__SLIF__IHBC__STATUS__SERVICE_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_FCS__SLIF__IHBC__STATUS__SERVICE_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/FCS_SLIF_IHBC_Status_ServiceStub.hpp>
#include <v1/commonapi/FCS_SLIF_IHBC_Status_ServiceSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

template <typename _Stub = ::v1::commonapi::FCS_SLIF_IHBC_Status_ServiceStub, typename... _Stubs>
class FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterInternal
    : public virtual FCS_SLIF_IHBC_Status_ServiceStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterHelper;

    ~FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterHelper::deinit();
    }

    void fireFCS_SLIF_IHBC_StatusAttributeChanged(const ::v1::commonapi::FCS_SLIF_IHBC_Status_Service::FCS_SLIF_IHBC_Status_Struct &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::FCS_SLIF_IHBC_Status_ServiceStub,
        CommonAPI::Version
    > getFCS_SLIF_IHBC_Status_ServiceInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::FCS_SLIF_IHBC_Status_ServiceStub,
        ::v1::commonapi::FCS_SLIF_IHBC_Status_Service::FCS_SLIF_IHBC_Status_Struct,
        ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_SLIF_IHBC_Status_StructDeployment_t
    > getFCS_SLIF_IHBC_StatusAttributeStubDispatcher;
    
    FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< FCS_SLIF_IHBC_Status_ServiceStub>(_stub)),
        getFCS_SLIF_IHBC_Status_ServiceInterfaceVersionStubDispatcher(&FCS_SLIF_IHBC_Status_ServiceStub::lockInterfaceVersionAttribute, &FCS_SLIF_IHBC_Status_ServiceStub::getInterfaceVersion, false, true),
        getFCS_SLIF_IHBC_StatusAttributeStubDispatcher(
            &::v1::commonapi::FCS_SLIF_IHBC_Status_ServiceStub::lockFCS_SLIF_IHBC_StatusAttribute,
            &::v1::commonapi::FCS_SLIF_IHBC_Status_ServiceStub::getFCS_SLIF_IHBC_StatusAttribute,
            false,
            _stub->hasElement(0))
    {
        FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1950) }, &getFCS_SLIF_IHBC_StatusAttributeStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>(0xFFFF, 0xFFFFFFFF, 0xFFFFFFFF);

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x9950)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x9950), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireFCS_SLIF_IHBC_StatusAttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::FCS_SLIF_IHBC_Status_ServiceStub>(_stub)->getFCS_SLIF_IHBC_StatusAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireFCS_SLIF_IHBC_StatusAttributeChanged(const ::v1::commonapi::FCS_SLIF_IHBC_Status_Service::FCS_SLIF_IHBC_Status_Struct &_value) {
    CommonAPI::Deployable< ::v1::commonapi::FCS_SLIF_IHBC_Status_Service::FCS_SLIF_IHBC_Status_Struct, ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_SLIF_IHBC_Status_StructDeployment_t> deployedValue(_value, static_cast< ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_SLIF_IHBC_Status_StructDeployment_t* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::commonapi::FCS_SLIF_IHBC_Status_Service::FCS_SLIF_IHBC_Status_Struct,
                ::v1::commonapi::FCS_SLIF_IHBC_Status_Service_::FCS_SLIF_IHBC_Status_StructDeployment_t
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x9950),
        false,
        deployedValue
    );
}


template <typename _Stub, typename... _Stubs>
void FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::commonapi::FCS_SLIF_IHBC_Status_ServiceStub, typename... _Stubs>
class FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapter
    : public FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          FCS_SLIF_IHBC_Status_ServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_FCS__SLIF__IHBC__Status__Service_SOMEIP_STUB_ADAPTER_HPP_
